UPLOAD = "UPLOAD"
DOWNLOAD = "DOWNLOAD"
LIST = "LIST"
DELETE = "DELETE"
EXIT = "EXIT"

HELLO = "HELLO"
HELLO_ACK = "HELLO_ACK"

READY = "READY"
FILE_FOUND = "FILE_FOUND"
FILE_NOT_FOUND = "FILE_NOT_FOUND"

TRANSFER_COMPLETE = "TRANSFER_COMPLETE"
INTEGRITY_OK = "INTEGRITY_OK"
INTEGRITY_FAILED = "INTEGRITY_FAILED"

UPLOAD_SUCCESS = "UPLOAD_SUCCESS"
UPLOAD_FAILED = "UPLOAD_FAILED"

DOWNLOAD_SUCCESS = "DOWNLOAD_SUCCESS"
DOWNLOAD_FAILED = "DOWNLOAD_FAILED"

DELETE_SUCCESS = "DELETE_SUCCESS"
DELETE_FAILED = "DELETE_FAILED"

ERROR = "ERROR"
GOODBYE = "GOODBYE"